### ISSUE TITLE
Cowling for Revo Voron

### ISSUE THREAD

**Issue by its-Blackpoint** [Yeriwyn/Salad_Fork#17]
Since there is no SaladFork Cowling for a Revo Voron Hotend, i made A remix. Please add it to Toolheads
[SaladFork_Revo_Cowling.stl.zip](https://github.com/PrintersForAnts/Salad_Fork/files/10282429/SaladFork_Revo_Cowling.stl.zip)

**Comment by Yeriwyn** [comment]
Done, thanks!
