### ISSUE TITLE
SF MiniSB cowling incompatible with v0.2 tool mounts

### ISSUE THREAD

**Issue by leothehuman** [Yeriwyn/Salad_Fork#19]
The cowling was probably taken from pre-release version and is symmetrical (has fillets on both left and right) and tool mounts from v0.2 are asymmetrical, with the chamfer on one side only.

**Comment by Yeriwyn** [comment]
I grabbed the latest toolhead from the v0 cad and updated the repo, does this fix the issue?

**Comment by leothehuman** [comment]
It does look like it will. Printing it now. Will update in the morning. Thank you!

**Comment by leothehuman** [comment]
Works perfectly now! Closing.
