### ISSUE TITLE
Missing picture in xy_motion.md

### ISSUE THREAD

**Issue by ccfman2004** [Yeriwyn/Salad_Fork#28]
You are missing the picture in xy_motion.md for the Motor A pulley mount orientation. You have it for Motor B but not motor A.

The image exists in the image folder of the docs but is not displayed in the actual xy_motion.md file.

https://github.com/PrintersForAnts/Salad_Fork/blob/master/docs/images/a_drive_pulley_detail.png

**Comment by Yeriwyn** [comment]
Weird, the markdown has the link for the image, will dig in to this

**Comment by Yeriwyn** [comment]
Fixed -- was a case-sensitivity thing where it couldn't find the image, thanks!

**Comment by ccfman2004** [comment]
Case sensitive stuff can be a real nightmare to figure out. I deal with that on Linux all the time.
