### ISSUE TITLE
Z_Chain Mount 3 hole and rear Z 2 hole

### ISSUE THREAD

**Issue by sbtoonz** [Yeriwyn/Salad_Fork#29]
https://github.com/PrintersForAnts/Salad_Fork/blob/master/STL/Frame/z_chain_mount_x1.stl
is a 3 hole mount and the rear Z is a 2 hole igus mount

would be nice if they matched so i didnt have to shrink a trident one down :D

**Comment by Yeriwyn** [comment]
there's a 2 hole variant z_chain_mount_2_hole_x1.stl in there too :)

**Comment by sbtoonz** [comment]
I'm blind 😂🔱
