### ISSUE TITLE
Incorrect links/page numbers in manual table of contents

### ISSUE THREAD

**Issue by indistinctTalk** [Yeriwyn/Salad_Fork#40]
Hey, thanks so much for this project and putting the manual together! I'm looking forward to rebuilding with 1.1.

Anyway, while perusing through I noticed the table of contents isn't always correct. Here's what I've found that I think should be updated.

- Klicky Assembly says 122 when it should be 121. The link is correct.
- Carriage and Belts says 132 and the link goes to 131, when they should be 130.
- Toolhead says 143 and the link goes to 157, when they should be 142.
- Skirts says 169 when it should be 168. The link is correct.
- Electronics says 186 when it should be 185. The link is correct.
- Panels says 210 when it should be 209. The link is correct.

Thanks again! 🎉

**Comment by Yeriwyn** [comment]
Off by one errors all over the place :) Thanks, I'll update the manual with these corrections

**Comment by Yeriwyn** [comment]
Resolved in [694513c](https://github.com/PrintersForAnts/Salad_Fork/commit/694513c300ca241492e7d4af3b2fa356fe56927d)
