### ISSUE TITLE
Possibility to add threaded heat sets to Feet

### ISSUE THREAD

**Issue by ccfman2004** [Yeriwyn/Salad_Fork#42]
Would it be possible to make the access holes that you mount the "[a]_m3_foot_base_x4.stl" take threaded heat sets? Because you are screwing into plastic with standard M3x6 BHCS it is way too easy to strip and make the foot base not secure enough. I don't know if there is enough space or plastic to be able to do this and I cannot CAD to save my life.

If that's not possible maybe a hole in the feet to add a heat set there rather than the foot base?

I would just feel better if the rubber feet were better secured to the plastic feet.

**Comment by indistinctTalk** [comment]
Hey @ccfman2004, I've had a go at this over at https://github.com/iJebus/Salad_Fork/commit/6712712652443905c42e0e1d8148e875392d3efe. Note that I can't say whether this is a good idea, and I haven't run any test prints yet.

All I've done is make the holes the same diameter as the heatset hole on `[a]_m3_foot_base_x4.stl` so... :shrug: That takes a heatset, these should too? 😅 The only thing I can think of is that the print orientation is different so some tweaking may be required around that.

An alternative to the heatset approach would be embedding nuts on the opposite face, which I imagine would be even more overkill.

**Comment by indistinctTalk** [comment]
Side note, agreed that the plastic is thinner here, and possibly too thin. Thickening it up shouldn't be an issue, aside from not matching the other skirt pieces unless they were also altered.

![image](https://github.com/user-attachments/assets/2f3ae82b-2b70-48b0-98ef-2b126d14d8c0)

**Comment by ccfman2004** [comment]
I'm going to print the test pieces to see how it goes. If that goes well maybe you can modify the rear two feet.

**Comment by ccfman2004** [comment]
It worked perfectly.  It feels so much more solid that before.

![IMG_7370](https://github.com/user-attachments/assets/dac1bc81-cb41-4509-b3f1-856e7ed18a11)
![IMG_7371](https://github.com/user-attachments/assets/7a01d711-b2b9-44f0-91f0-c04a35a028fc)

**Comment by indistinctTalk** [comment]
Nice! 🚀 

I've done the rear feet and have [uploaded the complete set to Printables](https://www.printables.com/model/951563-salad-fork-v11-heatset-feet). I hope it's okay that I've taken the liberty of using your photos, if not I'll quickly take them down.

**Comment by Yeriwyn** [comment]
Good stuff!

**Comment by ccfman2004** [comment]
> Nice! 🚀
> 
> I've done the rear feet and have [uploaded the complete set to Printables](https://www.printables.com/model/951563-salad-fork-v11-heatset-feet). I hope it's okay that I've taken the liberty of using your photos, if not I'll quickly take them down.

No problem using my photos. Thanks for asking. I'll print out the rear feet when I get a chance.

**Comment by indistinctTalk** [comment]
@ccfman2004 do you think this issue can be closed? You can reopen or message me directly if you have any issues and need parts modified.
